server:
  port: 8001
spring:
  application:
    name: demo-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zmy188/demo-spring-cloud-config-server.git     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 1564270655@qq.com                                            # git仓库的账号
          password: zmy0427                                            # git仓库的密码